# Generated by Django 5.0.1 on 2024-01-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
