# Generated by Django 5.0.1 on 2024-03-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
