# Generated by Django 5.0.1 on 2024-03-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cartitem_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
