# Generated by Django 5.0.1 on 2024-03-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cartitem_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
