# Generated by Django 5.0.1 on 2024-03-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_amount',
        ),
    ]
