# Generated by Django 5.0.1 on 2024-03-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_cartitem_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
