# Generated by Django 5.0.1 on 2024-03-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_cartitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total',
        ),
    ]
